apiVersion: v1
kind: Service
metadata:
  name: go-simple-webserver
  labels:
    app: go-simple-webserver
spec:
  selector:
    app: go-simple-webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
